Atlasian api fix
uktrade/atlassian-account-user-audit pull request #5
Opened 2022-07-26 11:42 UTC by gareth-e

Applies the following changes:
- Fixes the message format error.
- Add ECS logging
- Add extra logging detail throughout.
- Add extra configurable switches:
   - MAX_USER_AGE_MONTHS - Max age of a user - disable user if not logged in since this time - defaults to 3 months.
   - MAX_DISABLE_RATE - The maximum number of users that will be disabled in any one run. Defaults to 10
   - ENABLE_DEACTIVATIONS - Switch to enable or disable the user deactivation function. Defaults to False (users won't be disabled - script will display users that would have been).

2022-07-26 11:48 UTC, lgarvey commented on cleanup_atlassian.py
> +import ecs_logging
Minor pep violation.  We tend to group imports:

core python packages

3rd party 

app based imports

2022-07-26 11:50 UTC, lgarvey commented on cleanup_atlassian.py
> +EARLIST_USER_DATE = (datetime.today() - relativedelta(months=MAX_USER_AGE_MONTHS)).strftime("%d-%m-%Y")
Why not leave this as a datetime object then you won't have to re-parse it later on on line 74?

2022-07-26 11:51 UTC, lgarvey commented on cleanup_atlassian.py
> +ENABLE_DEACTIVATIONS = os.environ.get("ENABLE_DEACTIVATIONS", False)
You'll need to coerce this if it's passed in from an env var, because it'll be the boolean "True" or "False" presumably

one way to do it is ... 
```
TRUE_VALUES = ('on', 'yes', 'true')
ENABLE_DEACTIVATIONS = os.environ.get("ENABLE_DEACTIVATIONS", "").lower() in TRUE_VALUES
```

2022-07-26 11:55 UTC, lgarvey commented on cleanup_atlassian.py
> +        raise RuntimeError(f"MAX_USER_AGE_MONTHS is set to {MAX_USER_AGE_MONTHS}. You don't want to set this less than 1!")
You probably want to just exit(1) instead of throwing an exception, unless you are catching the exception in an outer block then exit-ing.

2022-07-26 13:11 UTC, gareth-e commented on cleanup_atlassian.py
> +        raise RuntimeError(f"MAX_USER_AGE_MONTHS is set to {MAX_USER_AGE_MONTHS}. You don't want to set this less than 1!")
Yeah, I did wonder about that. OK, done.

2022-07-26 13:21 UTC, gareth-e commented on cleanup_atlassian.py
> +ENABLE_DEACTIVATIONS = os.environ.get("ENABLE_DEACTIVATIONS", False)
Ah yes, you're right. The type comes out as 'string'.
Like the method there ⬆️
👍

2022-07-26 13:40 UTC, gareth-e commented on cleanup_atlassian.py
> +EARLIST_USER_DATE = (datetime.today() - relativedelta(months=MAX_USER_AGE_MONTHS)).strftime("%d-%m-%Y")
Yeah, I think the reason for it is this can also be supplied as a user parameter (I only spotted that a bit earlier when I was updating the readme). So it allows the user to enter a parameter in a friendly format (not that we use it this way though).

```markdown
- **with specific last active date**<br>
This example will disable users who have not logged in since specified date, to disable users who have not logged in since *1st April 2021* and, put reason as "automated cleanup script"<br>
```$python cleanup_atlassian.py --last-active 01-04-2021```
```
https://github.com/uktrade/atlassian-account-user-audit/blob/master/README.md?plain=1#L10#L12

2022-07-26 13:59 UTC, gareth-e commented on cleanup_atlassian.py
> +import ecs_logging
Fair shout. OK, grouped them.
I sorted alphabetically too (that gets a mention elsewhere too, it seems - and seems like a good idea).

2022-07-28 15:29 UTC, lgarvey requested changes
🚀

2022-07-28 15:29 UTC, lgarvey approved these changes

2022-07-28 15:35 UTC, merged